env: "local"
alias_length: 6

database:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "admin123"
  name: "url"

http_server:
  address: "localhost:8080"
  timeout: 4s
  idle_timeout: 60s